/* Real browser consent/import acceptance. All responses and player records are synthetic. */
const {chromium,firefox,webkit}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const root=path.resolve(process.env.MAIMAI_PARTY_FIXTURE||'output/party-browser');
const expected=JSON.parse(fs.readFileSync(path.join(root,'expected.json')));
const channels=(process.env.MAIMAI_BROWSER_CHANNELS||'chrome,msedge,firefox,webkit').split(',');
const record=p=>p.evaluate(id=>window.maimaiPersonal.record(window.maimaiResearchCatalog.catalog.find(c=>c.chart_id===id)),expected.chart);
async function loaded(page){await page.waitForFunction(()=>window.maimaiPersonal&&window.maimaiResearchCatalog&&document.querySelector('#songs')?.children.length>0);await page.evaluate(()=>window.maimaiPersonal.ready);}
async function importFile(page,name,remember=false){await page.evaluate(()=>{window.__personalUpdates=0;window.addEventListener('maimai-personal-change',()=>window.__personalUpdates++);});await page.locator('input[type=file]').setInputFiles(path.join(root,name+'.maimai.json.gz'));await page.getByRole('heading',{name:'Import player data?',exact:true}).waitFor();await page.getByLabel('Remember on this device',{exact:true}).setChecked(remember);await page.getByRole('button',{name:'Import data',exact:true}).click();await page.waitForFunction(()=>window.__personalUpdates>0);await page.locator('.player-dialog').waitFor({state:'hidden'});}
async function context(browser,{failLatest=false,failData=false}={}){const ctx=await browser.newContext(),requests=[],errors=[];let latestRequests=0,dataRequests=0;
  ctx.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
  await ctx.route('**/*',async route=>{const u=new URL(route.request().url());requests.push(u.href);if(u.protocol==='file:')return route.continue();if(!['maimai.party','report.example.invalid','localhost'].includes(u.hostname)){await route.abort();return;}
    if(u.pathname==='/private/party/latest.json'){latestRequests++;if(failLatest)return route.abort();return route.fulfill({json:{...expected.newOffer,object:{sha256:expected.newHash,bytes:expected.newBytes,path:'/private/party/data/'+expected.newHash+'.gz'}},headers:{'Cache-Control':'no-store'}});}
    if(u.pathname.startsWith('/private/party/data/')){dataRequests++;if(failData)return route.abort();return route.fulfill({body:fs.readFileSync(path.join(root,'newer.maimai.json.gz')),contentType:'application/gzip'});}
    const base=u.hostname==='maimai.party'?path.join(root,'site'):root;
    const name=u.hostname==='maimai.party'?(u.pathname==='/'?'index.html':u.pathname.slice(1)):(u.pathname==='/private/'?'hosted.html':'local.html');
    const file=path.resolve(base,name);if(!file.startsWith(base+path.sep)||!fs.existsSync(file))return route.fulfill({status:404,body:'Not found'});
    const type={'.html':'text/html','.js':'application/javascript','.json':'application/json','.css':'text/css','.webp':'image/webp'}[path.extname(file)]||'application/octet-stream';
    return route.fulfill({body:fs.readFileSync(file),contentType:type,headers:u.hostname==='maimai.party'?{}:{'Cross-Origin-Opener-Policy':'same-origin-allow-popups','Cross-Origin-Resource-Policy':'same-origin','Referrer-Policy':'no-referrer'}});
  });return {ctx,requests,errors,counts:()=>({latestRequests,dataRequests})};
}
(async()=>{
for(const channel of channels){console.log(channel+': launching');const browser=await (channel==='firefox'?firefox:channel==='webkit'?webkit:chromium).launch({headless:true,timeout:30000,env:{...process.env,APPDATA:path.join(root,'browser-runtime','roaming'),LOCALAPPDATA:path.join(root,'browser-runtime','local')},...(!['firefox','webkit'].includes(channel)?{channel}:{})});
try {
  let baseline;console.log(channel+': importing');
  {const h=await context(browser),p=await h.ctx.newPage();await p.goto('https://maimai.party/?version='+expected.version+'&view=catalog&chart='+expected.chart);await loaded(p);await importFile(p,'player',true);baseline=await record(p);assert.equal(baseline.achievement,982500);
    assert.equal(await p.locator('.player-history').count(),1);assert.match(await p.locator('.player-history').innerText(),/Recorded play/);
    await p.locator('#personal-recorded').selectOption('yes');assert.equal(await p.locator('#songs > *').count(),1);
    const sibling=await p.evaluate(id=>{const c=maimaiResearchCatalog.catalog.find(c=>c.chart_id===id);return maimaiResearchCatalog.catalog.find(x=>x.chart_id!==id&&x.source_container_id===c.source_container_id&&x.format===c.format)?.chart_id;},expected.chart);
    if(sibling){await p.evaluate(id=>{const u=new URL(location.href);u.searchParams.set('chart',id);history.pushState(null,'',u);dispatchEvent(new PopStateEvent('popstate'));},sibling);assert.equal(await p.locator('#personal-recorded').inputValue(),'');assert.equal(await p.locator('[data-chart-id="'+sibling+'"] .player-achievement').first().innerText(),'Personal chart match unavailable');await p.goBack();await p.locator('[data-chart-id="'+expected.chart+'"]').waitFor();}

    await p.getByRole('button',{name:'Clear personal filters',exact:true}).click();
    await p.locator('[data-sort-key=achievement]').click();assert.equal(await p.locator('#songs > *').first().getAttribute('data-chart-id'),expected.chart);
    await p.locator('#settings-toggle').focus();await p.keyboard.press('ArrowDown');assert.equal(await p.evaluate(()=>document.activeElement.id),'player-import');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'settings-toggle');
    await importFile(p,'newer',true);assert.equal((await record(p)).achievement,992000);
    await importFile(p,'player',true);assert.equal((await record(p)).achievement,992000);
    await p.reload();await loaded(p);assert.equal((await record(p)).achievement,992000);
    await p.locator('input[type=file]').setInputFiles({name:'bad.gz',mimeType:'application/gzip',buffer:Buffer.from('invalid')});await p.getByRole('heading',{name:'Player data could not be imported'}).waitFor();assert.equal((await record(p)).achievement,992000);await p.getByRole('button',{name:'Close',exact:true}).click();
    if(channel==='chrome')await p.screenshot({path:path.join(root,'personal-desktop.png'),fullPage:true});
    await p.setViewportSize({width:390,height:844});if(channel==='chrome')await p.screenshot({path:path.join(root,'personal-mobile.png'),fullPage:true});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
    assert.deepEqual(h.errors,[]);await h.ctx.close();}
  for(const source of [pathToFileURL(path.join(root,'local.html')).href,'http://localhost:9476/','https://report.example.invalid/private/']){
    console.log(channel+': handoff '+source.split(':')[0]);const h=await context(browser),report=await h.ctx.newPage();await report.goto(source);await report.locator('#open-maimai-party').waitFor();assert.equal(h.requests.filter(u=>u.startsWith('https://maimai.party')).length,0);assert.equal(h.counts().latestRequests,0);
    const next=h.ctx.waitForEvent('page');await report.locator('#open-maimai-party').click();const p=await next;await loaded(p);await p.getByRole('heading',{name:'Bring your data to maimai.party?',exact:true}).waitFor();assert.equal(await record(p),null);assert.equal(h.counts().dataRequests,0);
    await p.getByRole('button',{name:'Import data',exact:true}).click();await p.locator('.player-dialog').waitFor({state:'hidden'});await p.waitForFunction(()=>window.maimaiPersonal.enabled());
    const imported=await p.evaluate(async()=>maimaiPlayerData.decode(Uint8Array.from(atob(sessionStorage.getItem('maimai-player-session')),c=>c.charCodeAt(0))));assert.equal(imported.revision,source.startsWith('https:')?expected.newOffer.revision:expected.revision);if(source.startsWith('https:')){assert.equal((await record(p)).achievement,992000);assert.equal(h.counts().dataRequests,1);}else assert.deepEqual(await record(p),baseline);
    assert(h.requests.every(u=>!u.includes('Synthetic%20Player')&&!u.includes('982500')&&!u.includes('992000')));assert.deepEqual(h.errors,[]);await h.ctx.close();
  }
  // Current-tab imports survive refresh; device-storage failures preserve the old data.
  {const h=await context(browser),p=await h.ctx.newPage();await p.goto('https://maimai.party/');await loaded(p);await importFile(p,'player');await p.reload();await loaded(p);assert.equal((await record(p)).achievement,982500);
    await p.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='maimai-player-session')throw new DOMException('Synthetic quota failure','QuotaExceededError');return original.call(this,k,v);};});
    await p.locator('input[type=file]').setInputFiles(path.join(root,'newer.maimai.json.gz'));await p.getByRole('heading',{name:'Import player data?',exact:true}).waitFor();await p.getByRole('button',{name:'Import data',exact:true}).click();await p.getByRole('heading',{name:'Player data could not be imported',exact:true}).waitFor();assert.equal((await record(p)).achievement,982500);await h.ctx.close();}
  // A newer remembered snapshot offers missing older history, then reuses the merged state.
  {const h=await context(browser),seed=await h.ctx.newPage();await seed.goto('https://maimai.party/');await loaded(seed);await importFile(seed,'newer',true);
    const report=await h.ctx.newPage();await report.goto(pathToFileURL(path.join(root,'local.html')).href);
    let next=h.ctx.waitForEvent('page');await report.locator('#open-maimai-party').click();let p=await next;await loaded(p);await p.getByText('Your newer results will be kept.',{exact:false}).waitFor();await p.getByRole('button',{name:'Import data',exact:true}).click();await p.locator('.player-dialog').waitFor({state:'hidden'});await p.waitForFunction(()=>document.getElementById('player-status').textContent.includes('Remembered'));assert.equal((await record(p)).achievement,992000);
    next=h.ctx.waitForEvent('page');await report.locator('#open-maimai-party').click();p=await next;await loaded(p);await report.waitForFunction(()=>document.querySelector('.party-transfer-status')?.textContent.includes('already has'));assert.equal(await p.locator('.player-dialog:visible').count(),0);assert.equal((await record(p)).achievement,992000);
    await report.goto(pathToFileURL(path.join(root,'different.html')).href);next=h.ctx.waitForEvent('page');await report.locator('#open-maimai-party').click();p=await next;await loaded(p);await p.getByText('This switches the active player.',{exact:false}).waitFor();await p.getByRole('button',{name:'Continue without personal results',exact:true}).click();assert.equal(await record(p),null);
    const saved=await h.ctx.newPage();await saved.goto('https://maimai.party/');await loaded(saved);assert.equal((await record(saved)).achievement,992000);
    assert.deepEqual(h.errors,[]);await h.ctx.close();}
  // Failed hosted refresh offers an honestly dated embedded snapshot; interrupted payloads do not replace results.
  for(const failure of ['latest','data']){const h=await context(browser,{failLatest:failure==='latest',failData:failure==='data'}),report=await h.ctx.newPage();await report.goto('https://report.example.invalid/private/');const next=h.ctx.waitForEvent('page');await report.locator('#open-maimai-party').click();const p=await next;await loaded(p);await p.getByRole('heading',{name:'Bring your data to maimai.party?',exact:true}).waitFor();if(failure==='latest')await p.getByText('The hosted update was unavailable.',{exact:false}).waitFor();await p.getByRole('button',{name:'Import data',exact:true}).click();if(failure==='data'){await p.getByRole('heading',{name:'Player data could not be imported',exact:true}).waitFor();assert.equal(await record(p),null);}else{await p.locator('.player-dialog').waitFor({state:'hidden'});await p.waitForFunction(()=>window.maimaiPersonal.enabled());assert.equal((await record(p)).achievement,982500);}await h.ctx.close();}
  // A stale tab cannot overwrite a successful import in another tab.
  {const h=await context(browser),a=await h.ctx.newPage();await a.goto('https://maimai.party/');await loaded(a);await importFile(a,'player',true);const b=await h.ctx.newPage();await b.goto('https://maimai.party/');await loaded(b);await importFile(a,'newer',true);await b.locator('input[type=file]').setInputFiles(path.join(root,'different.maimai.json.gz'));await b.getByRole('heading',{name:'Import player data?',exact:true}).waitFor();await b.getByLabel('Remember on this device',{exact:true}).check();await b.getByRole('button',{name:'Import data',exact:true}).click();await b.getByRole('heading',{name:'Player data could not be imported',exact:true}).waitFor();assert.equal((await record(b)).achievement,982500);await b.reload();await loaded(b);assert.equal((await record(b)).achievement,992000);await h.ctx.close();}
  // Exact similarity opens automatically, survives reload, and restores on Back.
  {const h=await context(browser),report=await h.ctx.newPage();await report.goto(pathToFileURL(path.join(root,'local.html')).href);if(channel==='chrome'){await report.getByRole('tab',{name:'Targets',exact:true}).click();await report.screenshot({path:path.join(root,'report-targets.png'),fullPage:true});}
    await report.getByRole('tab',{name:'Scores',exact:true}).click();await report.locator('button[data-detail-source="plays"][data-detail-index="0"]').click();const next=h.ctx.waitForEvent('page');await report.getByRole('link',{name:'Find similar on maimai.party',exact:true}).click();const p=await next;await loaded(p);await p.getByRole('button',{name:'Continue without personal results',exact:true}).click();await p.locator('#similar-results h2').waitFor();assert.equal(new URL(p.url()).searchParams.get('left'),expected.chart);const title=await p.locator('#compare-left-search').inputValue();await p.reload();await loaded(p);await p.locator('#similar-results h2').waitFor();assert.equal(await p.locator('#compare-left-search').inputValue(),title);
    await p.evaluate(()=>{const u=new URL(location.href);u.searchParams.set('view','catalog');history.pushState(null,'',u);dispatchEvent(new PopStateEvent('popstate'));});await p.goBack();await p.locator('#similar-results h2').waitFor();assert.equal(await p.locator('#compare-left-search').inputValue(),title);assert.deepEqual(h.errors,[]);await h.ctx.close();}
  // Deep links retain exact chart selection through refusal; remembered data survives.
  {const h=await context(browser),report=await h.ctx.newPage();await report.goto(pathToFileURL(path.join(root,'local.html')).href);await report.getByRole('tab',{name:'Scores',exact:true}).click();await report.locator('button[data-detail-source="plays"][data-detail-index="0"]').click();const next=h.ctx.waitForEvent('page');await report.getByRole('link',{name:'See song details on maimai.party',exact:true}).click();const p=await next;await loaded(p);await p.getByRole('button',{name:'Continue without personal results',exact:true}).click();assert.equal(new URL(p.url()).searchParams.get('chart'),expected.chart);assert.equal(await p.locator('.player-history:visible').count(),0);assert.equal(await record(p),null);assert.deepEqual(h.errors,[]);await h.ctx.close();}
  console.log(channel+': file import, history merge, remembered reload, invalid-file preservation, mobile, consent, local/served/protected handoff, exact details and decline passed');
}finally{await browser.close();}
}
})().catch(e=>{console.error(e);process.exitCode=1;});
